// Amber-NAR © Karim Vergnes <me@thesola.io>
// Licensed under GNU GPLv2
// Main functions for navigating NAR archives

import { starts_with } from "std/text"

import { file_download } from "github.com/nixie-dev/amber-http2/http.ab"

import { read_nar_length, read_nar_string } from "./string.ab"

/// Returns the contents of a file within the NAR archive, by path.
pub fun cat_file(nar: Text, path: Text): Text?
{
    echo "Not yet implemented, sorry!"
    fail 1
}
